### ISSUE TITLE
MariaDB ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by jsbberlin** [akhoury/nodebb-plugin-import-ubb#5]
I cloned the ubb import in order to write my own importer for a self written forum.

I tried to import out of a MariaDB:

```
/usr/bin/mysql --version
/usr/bin/mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

```

and received the following error:

`ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client {"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlState":"08004","fatal":true}
`

Upgraded the mysql driver to
-        "mysql": "~2.4.2"
+        "mysql": "~2.18.1",

but error stayed the same.
Is there a recommendation to solve this problem?

**Comment by akhoury** [comment]
oof, maybe try using a different module all together, maybe this https://www.npmjs.com/package/mariadb

The importer plugins doesn't care how you get the data, as long as you maintain the API functions
https://github.com/akhoury/nodebb-plugin-import/blob/master/write-my-own-exporter.md

**Comment by jsbberlin** [comment]
I finally learned that ;-) My very first step, was to avoid those changes in order to understand how the importer works at all. I used another work around: dump restored into a mysql - that helped me in first place.
